# Generated by Django 6.0.7 on 2026-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Corporate', 'Corporate'), ('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Festival', 'Festival'), ('Exhibition', 'Exhibition'), ('Private Party', 'Private Party')], max_length=50),
        ),
    ]
