# Generated by Django 6.0.7 on 2026-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
